ALTER TABLE wallets ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at
    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN user_id int NOT NULL, MODIFY COLUMN balance bigint not
        null;


DESC wallets;